# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='test',
            field=models.TextField(default='test'),
        ),
    ]
