# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0002_county_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='county',
            table='counties',
        ),
    ]
