# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0003_auto_20171020_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Siting Model Name')),
                ('description', models.TextField(default='siting model description')),
                ('model_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
