# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0004_sitingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitingmodel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
