# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0005_sitingmodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitingmodel',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default Model'),
        ),
        migrations.AlterField(
            model_name='sitingmodel',
            name='description',
            field=models.TextField(default='siting model description', verbose_name='Model Description'),
        ),
    ]
