# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0006_auto_20171024_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitingmodel',
            name='county',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='siting.County'),
            preserve_default=False,
        ),
    ]
