# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0007_sitingmodel_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Layer Name')),
                ('description', models.TextField(default='siting model description', verbose_name='Layer Description')),
                ('sitingModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siting.SitingModel')),
            ],
        ),
    ]
